### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'run_async_query'

### ISSUE THREAD

**Issue by markstur** [IBM/tensorflow-kubernetes-art-classification#11]
I can't run bigquery.py as documented. Is it out-of-date or something in my python env?

Traceback (most recent call last):
  File "tensorflow-kubernetes-art-classification/bigquery.py", line 29, in <module>
    query_metart()
  File "tensorflow-kubernetes-art-classification/bigquery.py", line 13, in query_metart
    query_job = client.run_async_query(str(uuid.uuid4()), """
AttributeError: 'Client' object has no attribute 'run_async_query'

**Comment by tonanhngo** [comment]
I built a fresh environment and was able to replicate the problem.  Apparently the API for the Google BigQuery client was just changed.  Updating the code now.
